[MASS-144] Non-working changes on sample relation
pruned stacktrace:
    obj.save()
  File "/home/timm/Documents/mass_server_flask/venv_mass/lib/python3.5/site-packages/mongoengine/document.py", line 303, in save
    self.validate(clean=clean)
  File "/home/timm/Documents/mass_server_flask/venv_mass/lib/python3.5/site-packages/mongoengine/base/document.py", line 414, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (BaseSampleRelation.SampleRelation:None) (Field is required: ['other', 'sample', 'relation_type'])