On submit_dropped_by_sample_relation schema does not resolve URLs to References
mongoengine.errors.ValidationError: ValidationError (SampleRelation:None) (Field is required: ['other', 'sample'])